export const X_TREND_COPY = {
  metadataTitle: 'X 热搜',
  metadataDescription: '按小时更新的 X 热搜快照，展示最新成功抓取的多地区趋势榜单。',
  title: 'X 热搜',
  subtitle: '最新成功抓取的地区热搜快照，每个地区展示前 20 条趋势。',
  filterRegionPlaceholder: '地区',
  allRegions: '全部地区',
  updatedAtLabel: '更新于',
  regionsLabel: '地区数',
  itemsLabel: '条',
  emptyState: '暂无可展示的趋势数据。',
  errorLoad: '加载 X 热搜失败，请稍后重试。',
  errorNoSnapshot: '暂无 X 热搜抓取数据，请先执行 crawl:x:trending 或等待 CI 任务。',
  errorNoDbEnv: '数据库环境变量未配置，请检查 TURSO_DATABASE_URL 与 TURSO_AUTH_TOKEN。',
  errorNoTable: 'X 热搜表尚未初始化，请先执行一次 db:migrate。',
  errorQueryFailed: '读取 X 热搜数据失败，请稍后重试。',
} as const;
